title: Apps Espíritas
description: >-
  Aplicações gratuitas para o estudo do Espiritismo. Sem custo,
  sem publicidade e sem recolha de dados pessoais.
url: "https://appsespiritas.github.io"
baseurl: ""
lang: pt-PT
contacto_email: "appsespiritas@gmail.com"
formulario_google: "https://docs.google.com/forms/d/e/1FAIpQLSeHhIWaLvHiBDBMVvHVlE3uOGtH7t8y_LWrQGSAEzEIMturPg/viewform?embedded=true"

collections:
  apps:
    output: true
    permalink: /apps/:name/

defaults:
  - scope:
      path: ""
      type: apps
    values:
      layout: app

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor